services:
  app:
    image: "ghcr.io/mitschlcoding/next-drizz:latest"
    container_name: nextjs_production_app
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=80
    labels:
     - traefik.enable=true
     - traefik.http.routers.apache.rule=Host(`app.mitschl.de`)
     - traefik.http.routers.apache.entrypoints=web
    networks:
      - "proxy"

networks:
  proxy:
    external: true