services:
  app:
    image: "ghcr.io/mitschlcoding/next-drizz:latest"
    container_name: nextjs_production_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    labels:
     - traefik.enable=true
     - traefik.http.routers.apache.rule=Host(`app.example.com`)
     - traefik.http.routers.apache.entrypoints=web