version: '3.8'
services:
  app:
    image: ghcr.io/MitschlCoding/next-drizz:latest
    container_name: nextjs_production_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
